apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: common-latest
placementBindingDefaults:
  name: common-placement-binding
policyDefaults:
  # categories: []
  #controls:
  #  - PR.DS-1 Data-at-rest
  namespace: ztp-common
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    labelSelector:
      common: "true"
      du-profile: "latest"
  remediationAction: inform
  severity: low
  # standards: []
  namespaceSelector:
    exclude:
      - kube-*
    include:
      - '*'
  evaluationInterval:
    compliant: 10m
    noncompliant: 10s
policies:
- name: common-latest-config-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "1"
  manifests:
    - path: source-crs/cluster-tuning/monitoring-configuration/ReduceMonitoringFootprint.yaml
    - path: source-crs/disconnected-registry/DefaultCatsrc.yaml
      patches:
      - metadata:
          name: redhat-operators-disconnected
        spec:
          displayName: disconnected-redhat-operators
          image: registry.example.com:5000/disconnected-redhat-operators/disconnected-redhat-operator-index:v4.9
    - path: source-crs/disconnected-registry/DisconnectedIDMS.yaml
      patches:
      - spec:
          imageDigestMirrors:
          - mirrors:
            - registry.example.com:5000
            source: registry.redhat.io
- name: common-latest-subscriptions-policy
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
    # Logging operator
    - path: source-crs/cluster-logging/ClusterLogNS.yaml
    - path: source-crs/cluster-logging/ClusterLogOperGroup.yaml
    - path: source-crs/cluster-logging/ClusterLogSubscription.yaml
    - path: source-crs/cluster-logging/ClusterLogOperatorStatus.yaml
    - path: source-crs/cluster-logging/ClusterLogServiceAccount.yaml
    - path: source-crs/cluster-logging/ClusterLogServiceAccountAuditBinding.yaml
    - path: source-crs/cluster-logging/ClusterLogServiceAccountInfrastructureBinding.yaml
    # Ptp operator
    - path: source-crs/ptp-operator/PtpSubscriptionNS.yaml
    - path: source-crs/ptp-operator/PtpSubscription.yaml
    - path: source-crs/ptp-operator/PtpSubscriptionOperGroup.yaml
    - path: source-crs/ptp-operator/PtpOperatorStatus.yaml
    # SRIOV operator
    - path: source-crs/sriov-operator/SriovSubscriptionNS.yaml
    - path: source-crs/sriov-operator/SriovSubscriptionOperGroup.yaml
    - path: source-crs/sriov-operator/SriovSubscription.yaml
    - path: source-crs/sriov-operator/SriovOperatorStatus.yaml
    # Storage operator
    - path: source-crs/storage-lso/StorageNS.yaml
    - path: source-crs/storage-lso/StorageOperGroup.yaml
    - path: source-crs/storage-lso/StorageSubscription.yaml
    - path: source-crs/storage-lso/StorageOperatorStatus.yaml
    #
    # LCA operator is used for orchestrating Image Based Upgrade for SNO
    # - path: source-crs/lca/LcaSubscriptionNS.yaml
    # - path: source-crs/lca/LcaSubscriptionOperGroup.yaml
    # - path: source-crs/lca/LcaSubscription.yaml
    # - path: source-crs/lca/LcaOperatorStatus.yaml
    #
    # OADP operator is used for backing up and restoring application during Image Based Upgrade
    # - path: source-crs/data-protection/OadpSubscriptionNS.yaml
    # - path: source-crs/data-protection/OadpSubscriptionOperGroup.yaml
    # - path: source-crs/data-protection/OadpSubscription.yaml
    # - path: source-crs/data-protection/OadpOperatorStatus.yaml
