apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: example-reboot
placementBindingDefaults:
  name: example-reboot-placement-binding
policyDefaults:
  namespace: default
  placement:
    labelSelector:
      site: "example-reboot"
  remediationAction: inform
  severity: low
  namespaceSelector:
    exclude:
      - kube-*
    include:
      - '*'
  evaluationInterval:
    compliant: watch
    noncompliant: watch
policies:
- name: example-reboot
  policyAnnotations:
    ran.openshift.io/soak-seconds: "120"
  manifests:
  - path: source-crs/machine-config/RebootMachineConfig.yaml
    complianceType: mustonlyhave
    patches:
    - spec:
        config:
          storage:
            files:
            - contents:
              # content of file should change to trigger a reboot
              # append a message for the reboot to the content of the file
              # example: $ echo "$(date): applying tuned config" | base64
                source: data:text/plain;charset=utf-8;base64,bWVzc2FnZQo=
              mode: 420
              path: "/etc/kubernetes/mcp-reboot-flag"
      metadata:
        name: "95-reboot-<mcp>"
        labels:
          machineconfiguration.openshift.io/role: "<mcp>"
  - path: source-crs/validatorCRs/rebootMachineConfigPoolValidator.yaml
    complianceType: musthave
    patches:
    - metadata:
        name: "<mcp>"
      status:
        configuration:
          source:
            - apiVersion: machineconfiguration.openshift.io/v1
              kind: MachineConfig
              name: "95-reboot-<mcp>"
