apiVersion: ptp.openshift.io/v1
kind: PtpOperatorConfig
metadata:
  name: default
  namespace: openshift-ptp
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  {{- if .spec.daemonNodeSelector }}
  daemonNodeSelector:
    {{ template "matchNodeSelector" (list .spec.daemonNodeSelector "node-role.kubernetes.io" ) }}
  {{- end }}
  ptpEventConfig:
    enableEventPublisher: true
    {{- if and .spec.ptpEventConfig .spec.ptpEventConfig.apiVersion }}
    apiVersion: {{ .spec.ptpEventConfig.apiVersion | toYaml }}
    {{- end }}
    {{- if and .spec.ptpEventConfig .spec.ptpEventConfig.transportHost }}
    transportHost: {{ .spec.ptpEventConfig.transportHost | toYaml }}
    {{- end }}
