apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  # if you change this name make sure the 'include' line in TunedPerformancePatch.yaml
  # matches this name: include=openshift-node-performance-${PerformanceProfile.metadata.name}
  # Also in file 'validatorCRs/informDuValidator.yaml':
  # name: 50-performance-${PerformanceProfile.metadata.name}
  name: openshift-node-performance-profile
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
    ran.openshift.io/reference-configuration: "ran-du.redhat.com"
    {{- if .metadata }}
      {{ $allowedSysctls := (list
          "net.ipv6.conf.all.accept_ra"
          "net.ipv6.conf.default.accept_ra"
          "net.ipv6.conf.all.disable_ipv6"
          "net.ipv6.conf.default.disable_ipv6"
          "net.ipv4.conf.all.disable_policy"
          "net.ipv4.conf.default.disable_policy"
          "net.ipv6.conf.all.disable_policy"
          "net.ipv6.conf.default.disable_policy"
          "net.ipv4.conf.all.rp_filter"
          "net.ipv4.conf.default.rp_filter"
          "net.ipv6.conf.all.hop_limit"
          "net.ipv6.conf.default.hop_limit"
        ) }}
      {{- template "kubeletconfigExperimentalSysctls" (list (index (.metadata.annotations | default dict) "kubeletconfig.experimental") (list)  $allowedSysctls) }}
    {{- end }}
spec:
  additionalKernelArgs:
    {{- $requiredArgs := list
      "efi=runtime"
      "module_blacklist=irdma"
      "rcupdate.rcu_normal_after_boot=0"
    }}
    {{- $optionalArgs := list
      "vfio_pci.disable_idle_d3=1"
      "vfio_pci.enable_sriov=1"
    }}
    {{- if .spec.workloadHints.perPodPowerManagement }}
      {{- $optionalArgs = append $optionalArgs "cpufreq.default_governor=.*" }}
    {{- end }}
    {{- template "kernelArgList" (list .spec.additionalKernelArgs $requiredArgs $optionalArgs) }}
  cpu:
    isolated: {{ .spec.cpu.isolated }}
    reserved: {{ .spec.cpu.reserved }}
  # hardwareTuning allows maximum CPU frequencies to be set for reserved and isolated CPUs
  #hardwareTuning:
  #  isolatedCpuFreq: <max frequency in kHz>
  #  reservedCpuFreq: <max frequency in kHz>
  {{- if .spec.hardwareTuning }}
  {{- /* Require both isolatedCpuFreq and reservedCpuFreq are set (if this section is present), but allow any value */}}
  hardwareTuning:
    isolatedCpuFreq: {{ .spec.hardwareTuning.isolatedCpuFreq | default "Required - Must be a positive integer" }}
    reservedCpuFreq: {{ .spec.hardwareTuning.reservedCpuFreq | default "Required - Must be a positive integer" }}
  {{- end }}
  hugepages:
    defaultHugepagesSize: {{ .spec.hugepages.defaultHugepagesSize }}
    pages:
      {{- range .spec.hugepages.pages }}
      - size: {{ .size  }}
        count: {{ .count }}
        {{- if .node }}
        node: {{ .node }}
        {{- end }}
      {{- end }}
  {{- if .spec.kernelPageSize }}
  kernelPageSize: {{ .spec.kernelPageSize }}
  {{- end }}
  machineConfigPoolSelector:
    {{ template "matchNodeSelector" (list .spec.machineConfigPoolSelector "pools.operator.machineconfiguration.openshift.io" ) }}
  {{- if .spec.nodeSelector }}
  nodeSelector:
    {{ template "matchNodeSelector" (list .spec.nodeSelector "node-role.kubernetes.io" ) }}
  {{- end }}
  numa:
    topologyPolicy: "restricted"
  # To use the standard (non-realtime) kernel, set enabled to false
  realTimeKernel:
    enabled: {{ .spec.realTimeKernel.enabled }}
  workloadHints:
    # WorkloadHints defines the set of upper level flags for different type of workloads.
    # See https://github.com/openshift/cluster-node-tuning-operator/blob/master/docs/performanceprofile/performance_profile.md#workloadhints
    # for detailed descriptions of each item.
    # The configuration below is set for a low latency, performance mode.
    realTime: true
    highPowerConsumption: false
    perPodPowerManagement: {{ .spec.workloadHints.perPodPowerManagement | default false }}
