apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: $mcp 
  name: 95-talm-initiated-reboot-$mcp
spec:
  baseOSExtensionsContainerImage: ""
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,$data
        mode: 420
        path: /etc/kubernetes/reboot-$mcp
  fips: false
  kernelArguments: null
  kernelType: ""
  osImageURL: ""
